### ISSUE TITLE
Don't overwrite F3

### ISSUE THREAD

**Issue by BlaM** [skandasoft/navigate#15]
In a standard Atom installation F3 is "keymapped" to find-and-replace:find-next (which is the same behaviour almost every program in Windows has).

Navigate overwrites that though - and there is no way to stop it from doing so. For me that's a deal-breaker. All I want from this plugin is the F1 -> DevDocs binding.

My suggested solution would be to add an settings option to disable automatic keybindings - similar to this:

![image](https://cloud.githubusercontent.com/assets/176011/10937922/a67f1212-82f6-11e5-89cc-35e257e0b025.png)

**Comment by skandasoft** [comment]
can you not reconfigure key bindings and assign to a different  function key..

**Comment by BlaM** [comment]
Managed to do so after some attempts (managed to put it in the wrong scope first). So: No deal-breaker anymore.

Still: Overwriting system defaults (F3 is find next in almost every program - at least for Windows) is kind of going against usability basics.

**Comment by skandasoft** [comment]
I am some how used to(from my other system which I work has f2 and f3 to go in and out of the object). it is so easy to peek  in to file and come back f3..I understand where you come from. I do a ctr-f..and press enter..
