### ISSUE TITLE
Unexpected activation

### ISSUE THREAD

**Issue by AsaAyers** [skandasoft/navigate#2]
Not sure I have the best title for this one.

It seems like if I double click on any line that contains a string it will try to jump to that path.

``` Javascript
var BaseStore = require('./base.js');

let blacklist = {};

chrome.storage.sync.get('blacklist', setBlacklist);
```
- if I double click `BaseStore` it jumps to `./base.js`
- If I double click `blacklist` nothing happens.
- If I double click `storage` I think it's attempting to jump to `blacklist` (I get the exception from #1)
- In pulling these sample lines I would normally select a whole line by triple clicking. This causes a problem on `BaseStore` as it jumps when I don't actually want it to.

**Comment by skandasoft** [comment]
the latest patch should take care of it. Closing it (will keep the other one to keep track of issue). Feel free to open.
