### ISSUE TITLE
Option for new tab

### ISSUE THREAD

**Issue by AsaAyers** [skandasoft/navigate#3]
I actually didn't realize that when this navigates it replaces the tab I'm in. I expected it to just open in a new tab instead.

**Comment by skandasoft** [comment]
There is an option on settings to make the dblclick open a new window..it is switched off by default. or  you can use f4(funciton key) to navigate to new window..
f2/dblclick - same window.
f3 - back
f4 - new window.
please check and close

**Comment by AsaAyers** [comment]
I see the config [in your code](https://github.com/skandasoft/navigate/blob/master/lib/navigate.coffee#L13) but it isn't showing up in the settings window.

![screenshot 2015-02-24 06 42 46](https://cloud.githubusercontent.com/assets/324999/6348712/74da4e2a-bbf0-11e4-8e93-eaba15ced9a9.png)

**Comment by AsaAyers** [comment]
Restarting atom fixied it. I guess that doesn't get picked up immediately in an upgrade.
