### ISSUE TITLE
Navigate seems to do a simple filename match

### ISSUE THREAD

**Issue by AsaAyers** [skandasoft/navigate#4]
![screenshot 2015-02-24 06 53 32](https://cloud.githubusercontent.com/assets/324999/6348896/3d1786ae-bbf2-11e4-8865-0c3680bad4d3.png)

As I was testing I also inconsistently had an issue where this would pop up and I had to click the file twice. The first click seems to take me to my file, but the file selector remains open until I click the file again.

**Comment by skandasoft** [comment]
When there are multiple matches..it would let the user decide.From next time it is supposed to go directly there..you can refresh its memory using navigate:refresh/by selection the url/refresh(if you picked it wrongly)

Unfortunately I am not able to replicate this issue on my side..I would keep this open for some time..If I come across again..I will fix it.

**Comment by skandasoft** [comment]
Moved order of call to close the drop down. Please try and re-open the ticket in case there is stilll issues..!!
