### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by radjivF** [skandasoft/navigate#8]
Hi, 

First: your work looks awesome but the F1, F2, F3, F4 doesn't work on mac, I only have an access with ctrl+maj+P

**Comment by skandasoft** [comment]
just updated the keymap/navigate.cson for mac. check the latest...

But the best thing about this package is that you can add your own key combination for navigating to custom url you would want. 
steps to acheive this would be 
1. go to the package folder/navigate/keymaps/navigate.cson and add own key combination 
eg. cmd-f5: 'navigate:browser'
now go to the package folder/navigate/lib/config.coffee and maintain the key combination in this, it would be like this

  'CMD-F5':
    title: 'Some API Search'
    type: 'string'
    default: 'http://api.com/search?q=&searchterm'

you would put the website you would want to search on ....hope it makes sense..
